### ISSUE TITLE
ara record with ec2_facts

### ISSUE THREAD

**Issue by AnthonyWC** [dmsimard/ara#114]
I am trying to use ec2_facts into ara record:

```
---
- hosts: "{{ HOST_TAG }}"
  gather_facts: false
  become: no
  tasks:
  - name: Get instance ec2 facts
    action: ec2_facts
    register: ec2_facts

- debug:
     var: ec2_facts
     verbosity: 3
```

Haven't used ansible for awhile but I tried the following:
```
  - name: Record to ara
    ara_record:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
      type: "dict"
    with_dict: "{{ ec2_facts }}"
```

With the general format from register ec2_facts (from debug):
```
ok: [172.17.64.22] => {
    "ec2_facts": {
        "ansible_facts": {
            "ansible_ec2_ami_id": "ami-#####", 
            "ansible_ec2_ami_launch_index": "0", 
            "ansible_ec2_ami_manifest_path": "(unknown)", 
            "ansible_ec2_block_device_mapping_ami": "/dev/sda1", 
            "ansible_ec2_block_device_mapping_ebs3": "sdb", 
            "ansible_ec2_block_device_mapping_ebs4": "xvdf"
     }
}
ok: [172.17.64.23] => {
    "ec2_facts": {
        "ansible_facts": {
            "ansible_ec2_ami_id": "ami-######", 
            "ansible_ec2_ami_launch_index": "0", 
            "ansible_ec2_ami_manifest_path": "(unknown)"

  }
}
```

```
msg: module (ara_record) is missing interpreter line
fatal: [172.17.64.25]: FAILED! => {"failed": true, "msg": "module (ara_record) is missing interpreter line"}
```

**Comment by dmsimard** [comment]
Could you try something like this?

```
- ara_record:
    key: "ec2_facts"
    value: "{{ ec2_facts }}"
    type: "dict"
```

Otherwise, if you're looking for ansible facts (which probably picks up quite a few ec2 things), those are stored by default in ARA if you are gathering facts throughout your playbook.

**Comment by AnthonyWC** [comment]
Tried that but didn't work, I also tried quite a few variation like:

```
  - name: Record to ara
    ara_record:
      key: "{{ item }}"
      value: "{{ ec2_facts }}"
      type: "dict"
    with_items:
      - "{{ ec2_facts.ansible_facts.ansible_ec2_instance_id }}"
```

Or this (similar to debug later):
```
  - name: Record to ara
    ara_record:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
      type: "dict"
    with_items:
     - { key: "{{ ec2_facts.ansible_facts.ansible_ec2_instance_id }}", value: "{{ ec2_facts.ansible_facts }}" }
```
(tried to change type to "list", "dict", "json" and default as well)

This debug works:
```
- debug:
    msg: "key is {{ item.key }} Value is {{ item.value }}"
  with_items:
    - { key: "{{ ec2_facts.ansible_facts.ansible_ec2_instance_id }}", value: "{{ ec2_facts.ansible_facts }}" }
```

Give me output like these:
```
TASK [debug] *******************************************************************
ok: [172.17.64.22] => (item={u'value': {u'ansible_ec2_ami_launch_index': u'0',...
 u'key': u'i-##b####d'}) => {
    "item": {
        "key": "i-##b####d",
        "value": {
            "ansible_ec2_ami_id": "ami-f####90",
            "ansible_ec2_ami_launch_index": "0",
            "ansible_ec2_ami_manifest_path": "(unknown)",
            "ansible_ec2_block_device_mapping_ami": "/dev/sda1",...
 },
    "msg": "key is i-##b###d Value is {u'ansible_ec2_ami_launch_index': u'0', ..., u'ansible_ec2_block_device_mapping_root': u'/dev/sda1'}"
}
msg: All items completed
```

p.s. From GUI, individual host doesn't show ansible_facts since they are not "clickable"
